//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealtByOrder
    {
        public System.DateTime DealtDate { get; set; }
        public long SymbolId { get; set; }
        public string SymbolCode { get; set; }
        public Nullable<System.TimeSpan> DealtTime { get; set; }
        public long DealtId { get; set; }
        public Nullable<float> DealtPrice { get; set; }
        public Nullable<long> DealtVol { get; set; }
        public Nullable<bool> IsBuy { get; set; }
        public string BuyOrderId { get; set; }
        public Nullable<float> BuyPrice { get; set; }
        public string SellOrderId { get; set; }
        public Nullable<float> SellPrice { get; set; }
        public Nullable<long> BuyVol { get; set; }
        public Nullable<long> SellVol { get; set; }
        public Nullable<int> BuyOrderState { get; set; }
        public Nullable<int> SellOrderState { get; set; }
    }
}
