//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealtimeTick
    {
        public long SymbolID { get; set; }
        public string SymbolCode { get; set; }
        public string SymbolName { get; set; }
        public System.DateTime TickTime { get; set; }
        public Nullable<double> OpenPrice { get; set; }
        public Nullable<double> ClosePrice { get; set; }
        public Nullable<double> HighPrice { get; set; }
        public Nullable<double> LowPrice { get; set; }
        public Nullable<long> DealtVol { get; set; }
        public string BuyPrices { get; set; }
        public string SellPrices { get; set; }
        public string BuyVolms { get; set; }
        public string SellVolms { get; set; }
        public Nullable<double> UpperLimitPrice { get; set; }
        public Nullable<double> LowerLimitPrice { get; set; }
        public Nullable<long> CurrVolm { get; set; }
    }
}
